_text = str("Hello World")
_numeric = int(10)
_float = float(10.5)
_complex = complex(1j)
_lists = list(("appple", "banana", "mango"))
_tuple = tuple(("appple", "banana", "mango"))
_range = range(6)
_dict = dict(name="John", age=26)
_set = set(("apple", "banana", "mango"))
_frozenset = frozenset(("appple", "banana", "mango"))
_boolean = bool(True)
_bytes = bytes(5)
_byteArray = bytearray(5)
_memView = memoryview(bytes(5))
